import React,{useEffect,useState} from 'react';
import {Activity,ShieldAlert,Radio,Search,Plus,ChevronRight,LockKeyhole,Server,Network,ChartNoAxesCombined,RefreshCw,Send,CheckCircle2} from 'lucide-react';
import {ResponsiveContainer,AreaChart,Area,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';
import {api} from '../services/api.js';
import '../feedback.css';
import '../performance.css';
import '../dashboard-layout.css';
import Metric from '../components/MetricCard.jsx';

const categoryColors=['#7c5cff','#ff6b6b','#ffb84d','#32c9a2','#55a8ff','#dc78bc','#91c46a','#8492a6'];
const initial='Suspicious activity observed on an endpoint. Include source IP, affected system, and relevant indicators for an analyst report.';
export default function Dashboard(){
 const [text,setText]=useState(''); const [analysis,setAnalysis]=useState(null); const [metrics,setMetrics]=useState({}); const [overview,setOverview]=useState({}); const [history,setHistory]=useState([]); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [health,setHealth]=useState('checking'); const [feedback,setFeedback]=useState(''); const [activityCategory,setActivityCategory]=useState('all');
 const refresh=async()=>{try{const [h,m,o,i]=await Promise.all([api.health(),api.metrics(),api.overview(),api.history()]);setHealth(h.models);setMetrics(m);setOverview(o);setHistory(i.items||[])}catch{setHealth('offline')}};
 useEffect(()=>{refresh()},[]);
 const submit=async(e)=>{e.preventDefault();setBusy(true);setError('');setAnalysis(null);try{const value=await api.analyze({incident_text:text});setAnalysis(value)}catch(err){setError(err.message)}finally{setBusy(false)}};
 const selected=metrics.threat_category?.selected_model;
 const activityData=activityCategory==='all'?(overview.activity||[]):(overview.activity_by_category?.[activityCategory]||[]);
 const selectedActivityLabel=activityCategory==='all'?'All categories':activityCategory;
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><ShieldAlert size={21}/></div><div><b>SENTINEL</b><small>THREAT OPERATIONS</small></div></div><div className="workspace"><span className="live-dot"/> LIVE ENVIRONMENT <ChevronRight size={14}/></div><nav><span className="nav-label">WORKSPACE</span><a className="active"><Activity size={17}/> Overview</a><a onClick={()=>document.querySelector('#analyze')?.scrollIntoView({behavior:'smooth'})}><Radio size={17}/> Incident analysis</a><a onClick={()=>document.querySelector('#history')?.scrollIntoView({behavior:'smooth'})}><Search size={17}/> Incident history</a><a><ChartNoAxesCombined size={17}/> Model performance</a><span className="nav-label lower">MANAGEMENT</span><a><LockKeyhole size={17}/> Access control</a><a><Server size={17}/> Integrations</a></nav><div className="sidebar-bottom"><div className="secure"><LockKeyhole size={16}/><div><b>Secure workspace</b><small>Events processed locally</small></div></div><div className="user"><div className="avatar">SA</div><div><b>SOC Analyst</b><small>Security operations</small></div><span className="ellipsis">···</span></div></div></aside>
 <main className="main"><header className="topbar"><div className="crumb">Workspace <span>/</span> <b>Overview</b></div><div className="top-actions"><span className={`service ${health==='ready'?'':'dim'}`}><i/> Models {health}</span><button className="icon-button" onClick={refresh} title="Refresh"><RefreshCw size={16}/></button><div className="avatar">SA</div></div></header><div className="content"><section className="page-heading"><div><div className="eyebrow">SECURITY OPERATIONS CENTER <span>•</span> 24 HOUR VIEW</div><h1>Threat overview</h1><p>Monitor, investigate, and respond to security incidents.</p></div><button className="primary" onClick={()=>document.querySelector('#analyze')?.scrollIntoView({behavior:'smooth'})}><Plus size={17}/> New analysis</button></section>
 <section className="stats"><Metric icon={<Activity/>} label="Incidents monitored" value={overview.total_incidents?.toLocaleString()??'—'} change="Dataset records" tone="violet"/><Metric icon={<ShieldAlert/>} label="High / critical" value={overview.high_critical?.toLocaleString()??'—'} change="Dataset severity labels" tone="red"/><Metric icon={<Network/>} label="Threat categories" value={overview.threat_categories??'—'} change="Observed target classes" tone="amber"/><Metric icon={<Radio/>} label="Model status" value={health==='ready'?'Online':'Offline'} change={selected?`Selected: ${selected}`:'Train models to enable'} tone="green"/></section>
 <section className="grid two"><article className="panel chart-panel"><div className="panel-title"><div><h2>Incident activity</h2><p>{selectedActivityLabel} · counts across the latest 7 dataset dates</p></div><select className="select" aria-label="Filter incident activity by threat category" value={activityCategory} onChange={e=>setActivityCategory(e.target.value)}><option value="all">All categories</option>{(overview.categories||[]).map(x=><option key={x.name} value={x.name}>{x.name}</option>)}</select></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={activityData} margin={{left:-20,right:6,top:12,bottom:0}}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#7c5cff" stopOpacity={.3}/><stop offset="95%" stopColor="#7c5cff" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#1c2a3b" vertical={false}/><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{fill:'#718198',fontSize:10}}/><YAxis allowDecimals={false} tickLine={false} axisLine={false} tick={{fill:'#718198',fontSize:11}}/><Tooltip contentStyle={{background:'#101b2b',border:'1px solid #26364a',borderRadius:9}}/><Area type="monotone" dataKey="value" stroke="#8b72ff" strokeWidth={2.5} fill="url(#fill)"/></AreaChart></ResponsiveContainer></div></article>
 <article className="panel"><div className="panel-title"><div><h2>Threat categories</h2><p>Observed dataset class distribution</p></div><button className="more">···</button></div><div className="bars">{(overview.categories||[]).map((x,i)=><div className="bar-row" key={x.name}><div><span>{x.name}</span><b>{x.count.toLocaleString()}</b></div><div className="track"><i style={{width:`${overview.total_incidents?100*x.count/overview.total_incidents:0}%`,background:categoryColors[i%categoryColors.length]}}/></div></div>)}</div><div className="chart-note"><span><i className="live-dot"/> Counts from cleaned historical labels</span></div></article></section>
 <section className="panel model-performance" id="model-performance"><div className="panel-title"><div><h2>Model performance</h2><p>Actual held-out metrics from the latest training run</p></div><button className="text-button" onClick={refresh}>Refresh report <RefreshCw size={14}/></button></div>{['threat_category','severity_level'].some(k=>metrics[k]?.final_test)?<div className="performance-grid">{['threat_category','severity_level'].map(k=>{const m=metrics[k];return <div className="performance-card" key={k}><h3>{k==='threat_category'?'Threat category':'Severity'} <span>{m?.selected_model||'Not trained'}</span></h3>{m?.final_test?<div className="performance-numbers"><div><small>Test macro F1</small><b>{m.final_test.macro_f1.toFixed(3)}</b></div><div><small>Test weighted F1</small><b>{m.final_test.weighted_f1.toFixed(3)}</b></div><div><small>Test accuracy</small><b>{m.final_test.accuracy.toFixed(3)}</b></div></div>:<p>No completed experiment.</p>}</div>})}</div>:<div className="empty"><ChartNoAxesCombined size={21}/><b>No model evaluation report yet</b><span>Run the training pipeline to populate this panel.</span></div>}</section>
 <section className="panel analyze" id="analyze"><div className="panel-title"><div><div className="eyebrow">ANALYST WORKBENCH</div><h2>Analyze an incident</h2><p>ML models classify the event. AI assistance prepares investigation guidance.</p></div><span className="tag"><LockKeyhole size={13}/> Human reviewed</span></div><form onSubmit={submit}><label htmlFor="incident">Incident description</label><textarea id="incident" value={text} onChange={e=>setText(e.target.value)} placeholder={initial} minLength={5} required/><div className="form-bottom"><small>Do not include credentials or secrets. Text is sent to your configured API.</small><button className="primary" disabled={busy||text.length<5}>{busy?<><RefreshCw className="spin" size={15}/> Analyzing…</>:<>Run analysis <Send size={15}/></>}</button></div></form>{error&&<div className="error">{error}</div>}{analysis&&<Analysis result={analysis}/>}</section>
 <section className="panel history" id="history"><div className="panel-title"><div><h2>Recent incidents</h2><p>Latest records from PostgreSQL</p></div><button className="text-button" onClick={refresh}>Refresh <RefreshCw size={14}/></button></div>{history.length?<div className="table-wrap"><table><thead><tr><th>INCIDENT</th><th>CLASSIFICATION</th><th>SEVERITY</th><th>TIMESTAMP</th><th></th></tr></thead><tbody>{history.map(row=><tr key={row.incident_id}><td className="id">{row.incident_id}</td><td>{row.threat_category||'—'}</td><td><span className={`severity ${(row.severity_level||'').toLowerCase()}`}>{row.severity_level||'Unclassified'}</span></td><td>{row.timestamp?new Date(row.timestamp).toLocaleString():'—'}</td><td><ChevronRight size={16}/></td></tr>)}</tbody></table></div>:<div className="empty"><Search size={21}/><b>No stored incidents yet</b><span>Complete an analysis to create a record.</span></div>}</section>
 <footer>Sentinel SOC <span>•</span> Cybersecurity Incident Intelligence <span className="footer-right">ML classifications are separate from AI recommendations</span></footer></div></main></div>
}
function Analysis({result}){const p=result.prediction||{};const llm=result.llm_analysis||{};return <div className="result"><div className="result-header"><div><span className="eyebrow">MODEL PREDICTION</span><h3>{p.threat_category} <span className="confidence">{(p.threat_confidence*100).toFixed(1)}% confidence</span></h3><p>{p.incident_id} · Severity <b>{p.severity_level}</b> ({(p.severity_confidence*100).toFixed(1)}%)</p>{result.llm_status==='unavailable'&&<small>Gemini unavailable; prediction saved without AI assistance.</small>}</div><span className="result-icon"><CheckCircle2/></span></div><div className="result-columns"><div><h4>Extracted indicators</h4><div className="chips">{Object.entries(p.extracted_entities||{}).flatMap(([kind,items])=>items.map(item=><span key={kind+item}>{kind}: {item}</span>)).slice(0,20)}</div><h4>MITRE ATT&amp;CK references</h4><div className="chips">{[...(p.mitre_information?.techniques||[]),p.mitre_information?.provided_technique].filter(Boolean).map(x=><span key={x}>{x}</span>)}</div><h4>Top model factors</h4><ul>{(p.top_factors||[]).map((x,i)=><li key={i}>{x}</li>)}</ul><h4>Similar incidents</h4>{(p.similar_incidents||[]).length?<ul>{p.similar_incidents.map(x=><li key={x.incident_id}>{x.incident_id} · {x.threat_category} · {(x.similarity_score*100).toFixed(1)}%</li>)}</ul>:<small>No similarity artifact found. Train the pipeline to enable retrieval.</small>}</div><div className="recommendation"><span className="eyebrow">LLM RECOMMENDATION · HUMAN REVIEW REQUIRED</span><p>{llm.summary||'No summary returned.'}</p><h4>Investigation guidance</h4><ul>{(llm.investigation_steps||[]).map((x,i)=><li key={i}>{x}</li>)}</ul><h4>Recommended actions</h4><ul>{(llm.recommended_actions||[]).map((x,i)=><li key={i}>{x}</li>)}</ul></div></div><FeedbackForm prediction={p}/></div>}
function FeedbackForm({prediction}){const [category,setCategory]=useState('');const [severity,setSeverity]=useState('');const [comment,setComment]=useState('');const [correct,setCorrect]=useState(false);const [falsePositive,setFalsePositive]=useState(false);const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);setStatus('');try{await api.feedback({incident_id:prediction.incident_id,predicted_category:prediction.threat_category,correct_category:correct?prediction.threat_category:category||null,predicted_severity:prediction.severity_level,correct_severity:correct?prediction.severity_level:severity||null,false_positive:falsePositive,feedback:comment});setStatus('Feedback recorded for review. It will not update production models automatically.')}catch(err){setStatus(err.message)}finally{setBusy(false)}};return <form className="feedback-form" onSubmit={submit}><h4>Analyst feedback</h4><label><input type="checkbox" checked={correct} onChange={e=>setCorrect(e.target.checked)}/> Both predictions are correct</label><div className="feedback-grid"><input aria-label="Correct threat category" placeholder="Correct category (if changed)" value={category} onChange={e=>setCategory(e.target.value)}/><input aria-label="Correct severity" placeholder="Correct severity (if changed)" value={severity} onChange={e=>setSeverity(e.target.value)}/></div><label><input type="checkbox" checked={falsePositive} onChange={e=>setFalsePositive(e.target.checked)}/> Mark as false positive</label><textarea aria-label="Analyst comments" placeholder="Analyst comments" value={comment} onChange={e=>setComment(e.target.value)}/><button className="text-button" disabled={busy}>{busy?'Submitting…':'Submit feedback'}</button>{status&&<small>{status}</small>}</form>}
